---
title: "Workflow to release an R package to CRAN"
description: |
  A guide for users of both the GitHub worflow and Gitflow workflow.
author:
  - name: Mauro Lepore
    url: https://github.com/maurolepore
base_url: https://2degreesinvesting.github.io/
date: 2021-10-22
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: true
categories:
  - r2dii
  - package
  - release
  - workflow
preview: preview.jpg
twitter:
  site: "@mauro_lepore"
  creator: "@mauro_lepore"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>"
)
```

The goal of this post is to help you release an R package to CRAN. It works
whether you use the [GitHub
workflow](https://guides.github.com/introduction/flow/)
([video](https://youtu.be/WuB-RV7tigc)) or the [Gitflow
workflow](https://nvie.com/posts/a-successful-git-branching-model/)[^6]
([video](https://youtu.be/y6wY9ERBA4I)).

[^6]: If you use the Gitflow workflow, this article assumes you a) use the [`git
flow`](https://github.com/nvie/gitflow) extension and b) have privileges to push
to `origin/master` and `origin/develop`.

### Prepare for release

Consider the release of
[maurolepore/releaseworkflow](https://github.com/maurolepore/releaseworkflow)
`v0.0.1`[^1].

[^1]: See Mauro's
[aliases](https://github.com/maurolepore/dotfiles/blob/master/aliases.zsh) under
the section "CRAN release".

* Create a release checklist with `usethis::use_release_issue()`[^2].

[^2]: Ensure your remote `origin` points to the source repo (i.e. your remote setup is "[Ours](https://happygitwithr.com/common-remote-setups.html)"). This will fail if your remote `origin` points elsewhere (e.g. your fork).

* Create a new feature/branch[^3] (e.g. `prepare-v0.0.1`) and follow the release
checklist until the end of the section "Prepare for release"
([tweaks](https://github.com/2DegreesInvesting/resources/issues/198)).

[^3]: This branch is special only in the [gitflow
workflow](https://nvie.com/posts/a-successful-git-branching-model/); in the
[github workflow](https://guides.github.com/introduction/flow/) it's just like
any branch other than `master`.

### Did anything change?

* **Yes** -- the package is not ready for release yet:

    * Merge the feature/branch and repeat the main steps under "Prepare for
    release" until doing so changes nothing.

* **No** -- the package is ready for release: 

    *  Delete the feature/branch `prepare-v0.0.1` and create a release/branch
    `v0.0.1`[^3].
    
    *  Increment the version number with `usethis::use_version()`.
    
    *  Submit a pull request based on `master` and confirm clean CI.
    
    * `devtools::submit_cran()`. This adds CRAN-RELEASE -- delete it.

### Create GitHub release

Regardless of CRAN create a GitHub release:

* Merge the release branch into `master`, checkout `master`, and run
`usethis::use_github_release()`[^2] to create a new tag `v0.0.1`[^4] and a
corresponding GitHub release.

[^4]: The [`git flow`](https://github.com/nvie/gitflow) extension prompts you to
enter the tag manually. Use the form `vx.y.z` like
`usethis::use_github_release()` does. This avoids tagging the same commit twice.

* If you're using the [gitflow
workflow](https://nvie.com/posts/a-successful-git-branching-model/), ensure the
release branch is also merged into `develop`[^5] and checkout `develop` now.

[^5]: The [`git flow`](https://github.com/nvie/gitflow) merges release features
automatically into both `master` and `devleop` (see
https://bit.ly/gitflow-table).

### Continue development

* Increment the version number with `usethis::use_dev_version()`.

You can continue development. If CRAN accepts the submission, then the new tag
on `master` and GitHub release will also have a corresponding CRAN release.