---
title: "Getting data from the web"
description: |
  What every analyst and developer show know.
author:
  - name: Mauro Lepore
    url: https://github.com/maurolepore
base_url: https://2degreesinvesting.github.io/
date: 2000-02-04
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: true
categories:
  - draft
preview: preview.jpg
twitter:
  site: "@mauro_lepore"
  creator: "@mauro_lepore"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This post follows a series of ds-incubator meetups about getting data from the
web. It gathers what every developer and analyst should know:

1. The resources to learn more about the data for the PASTAX project that is
becoming available to you.
2. The resources to learn more about getting data from the web in general.
3. The main takeaways.

--

Data for the PASTAX project are becomming available. You can explore and
download it with the [app](https://twodii.shinyapps.io/pastax-data/),
read its [documentation](https://2degreesinvesting.github.io/pastax.data/reference) on
the pastax [website](https://2degreesinvesting.github.io/pastax.data), and use
it in R with the pastax.data [package](https://github.com/2DegreesInvesting/pastax.data).

To learn more about getting data from the web in general see the ds-incubator
[materials on github](https://github.com/2DegreesInvesting/ds.webdata), or the
[playlist on
YouTube](https://youtube.com/playlist?list=PLvgdJdJDL-AN_PBkgdD7xgrINsxYUPbwC).

In short, you can get data from most websites but the effort varies. The job is
easiest and most reproducible when:

* The website offers an Application Programming Inerface (API).
* The data has a clear structure, e.g. a table.
* You don't need to interact much, e.g. the data is available with no login nor
clicks.
* The data takes only a few seconds to download.

First you should always search for useful
[APIs](https://github.com/2DegreesInvesting/resources/issues/295) and
[packages](https://r-hub.github.io/pkgsearch/). To work with APIs in R you can
use the package [httr2](https://httr2.r-lib.org/index.html).

If you lack an API you may still scrape the data but it's genrally harder and
less reproducible. To scrape data from any website in R you can use the package
[rvest](https://rvest.tidyverse.org/). Do it
[ethically](https://towardsdatascience.com/ethics-in-web-scraping-b96b18136f01).
